TOKEN = '1421502925:AAHy5WOD-kIT4IyitCFalEkhruWHAghpJCM' #bot token
CURRENT_NODE_INDEX = 0

WHITE_POINT_INCREMENT = 'WHITE_POINT_INCREMENT'
BLACK_POINT_INCREMENT = 'BLACK_POINT_INCREMENT'
RED_POINT_INCREMENT = 'RED_POINT_INCREMENT'
CLEAR_POINTS = 'CLEAR_POINTS'